# Generated by Django 2.0 on 2018-06-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mxene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('M1', models.CharField(max_length=3)),
                ('M2', models.CharField(max_length=3)),
                ('X', models.CharField(max_length=3)),
                ('T1', models.CharField(max_length=3)),
                ('T2', models.CharField(max_length=3)),
                ('Lc', models.FloatField(null=True)),
                ('Bg', models.FloatField(null=True)),
                ('Mm', models.FloatField(null=True)),
                ('poscar_file', models.FileField(upload_to='media/poscars')),
                ('bands_image', models.ImageField(default='static/mxn_search/no_band_sorry.png', upload_to='media/images')),
            ],
        ),
    ]
