# Generated by Django 2.0 on 2018-06-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxn_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxene',
            name='bands_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
