# Generated by Django 2.0 on 2018-06-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxn_search', '0002_auto_20180622_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxene',
            name='poscar_file',
            field=models.FileField(upload_to='poscars'),
        ),
    ]
