# Generated by Django 2.0 on 2018-06-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxn_search', '0003_auto_20180626_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxene',
            name='bands_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
