# Generated by Django 2.0 on 2020-08-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardness_superalloy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
