# Generated by Django 2.0 on 2018-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnantApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('app_url', models.CharField(max_length=15)),
                ('app_image', models.ImageField(upload_to='media/app_images')),
            ],
        ),
    ]
